#!/usr/bin/env node

var app = require('./app.js');
var http = require('http');

var port = process.env.PORT || 3333;

app.set('port', port);

var server = http.createServer(app);

server.listen(port);
server.on('error', onError);

function onError(error) {
    if (error.syscall !== 'listen') {
        throw error;
    }

    switch (error.code) {
        case 'EACCES':
            console.error('Port ' + port + ' requires elevated privileges');
            process.exit(1);
            break;
        case 'EADDRINUSE':
            console.error('Port ' + port + ' is already in use');
            process.exit(1);
            break;
        default:
            throw error;
    }
}